// 365 English words for the "Palabra del Día" feature
// Each word includes translation, example in English/Spanish, and pronunciation guide

export const ENGLISH_WORDS = [
    { word: "Love", translation: "Amor", exampleEn: "I love you more every day", exampleEs: "Te amo más cada día", pronunciation: "lʌv" },
    { word: "Beautiful", translation: "Hermoso/a", exampleEn: "You look beautiful today", exampleEs: "Te ves hermosa hoy", pronunciation: "ˈbjuːtɪfəl" },
    { word: "Together", translation: "Juntos", exampleEn: "We are better together", exampleEs: "Somos mejores juntos", pronunciation: "təˈɡeðər" },
    { word: "Heart", translation: "Corazón", exampleEn: "You stole my heart", exampleEs: "Robaste mi corazón", pronunciation: "hɑːrt" },
    { word: "Dream", translation: "Sueño", exampleEn: "You are my dream come true", exampleEs: "Eres mi sueño hecho realidad", pronunciation: "driːm" },
    { word: "Happiness", translation: "Felicidad", exampleEn: "You bring me happiness", exampleEs: "Me traes felicidad", pronunciation: "ˈhæpɪnəs" },
    { word: "Forever", translation: "Para siempre", exampleEn: "I want to be with you forever", exampleEs: "Quiero estar contigo para siempre", pronunciation: "fərˈevər" },
    { word: "Smile", translation: "Sonrisa", exampleEn: "Your smile lights up the room", exampleEs: "Tu sonrisa ilumina la habitación", pronunciation: "smaɪl" },
    { word: "Kiss", translation: "Beso", exampleEn: "Give me a kiss", exampleEs: "Dame un beso", pronunciation: "kɪs" },
    { word: "Hug", translation: "Abrazo", exampleEn: "I need a hug from you", exampleEs: "Necesito un abrazo tuyo", pronunciation: "hʌɡ" },
    { word: "Darling", translation: "Cariño", exampleEn: "Good morning, darling", exampleEs: "Buenos días, cariño", pronunciation: "ˈdɑːrlɪŋ" },
    { word: "Sweet", translation: "Dulce", exampleEn: "You are so sweet", exampleEs: "Eres tan dulce", pronunciation: "swiːt" },
    { word: "Promise", translation: "Promesa", exampleEn: "I promise to always be there", exampleEs: "Prometo estar siempre ahí", pronunciation: "ˈprɑːmɪs" },
    { word: "Trust", translation: "Confianza", exampleEn: "I trust you completely", exampleEs: "Confío en ti completamente", pronunciation: "trʌst" },
    { word: "Grateful", translation: "Agradecido/a", exampleEn: "I am grateful for you", exampleEs: "Estoy agradecido por ti", pronunciation: "ˈɡreɪtfəl" },
    { word: "Adventure", translation: "Aventura", exampleEn: "Every day is an adventure with you", exampleEs: "Cada día es una aventura contigo", pronunciation: "ədˈventʃər" },
    { word: "Sunset", translation: "Atardecer", exampleEn: "Let's watch the sunset", exampleEs: "Veamos el atardecer", pronunciation: "ˈsʌnset" },
    { word: "Morning", translation: "Mañana", exampleEn: "Every morning with you is perfect", exampleEs: "Cada mañana contigo es perfecta", pronunciation: "ˈmɔːrnɪŋ" },
    { word: "Night", translation: "Noche", exampleEn: "Good night, my love", exampleEs: "Buenas noches, mi amor", pronunciation: "naɪt" },
    { word: "Always", translation: "Siempre", exampleEn: "I will always choose you", exampleEs: "Siempre te elegiré", pronunciation: "ˈɔːlweɪz" },
    { word: "Wonderful", translation: "Maravilloso/a", exampleEn: "You are a wonderful person", exampleEs: "Eres una persona maravillosa", pronunciation: "ˈwʌndərfəl" },
    { word: "Brave", translation: "Valiente", exampleEn: "You are so brave", exampleEs: "Eres tan valiente", pronunciation: "breɪv" },
    { word: "Cozy", translation: "Acogedor", exampleEn: "Our home is so cozy", exampleEs: "Nuestro hogar es tan acogedor", pronunciation: "ˈkoʊzi" },
    { word: "Cherish", translation: "Valorar", exampleEn: "I cherish every moment with you", exampleEs: "Valoro cada momento contigo", pronunciation: "ˈtʃerɪʃ" },
    { word: "Cuddle", translation: "Acurrucarse", exampleEn: "Let's cuddle on the couch", exampleEs: "Acurrucémonos en el sofá", pronunciation: "ˈkʌdəl" },
    { word: "Breakfast", translation: "Desayuno", exampleEn: "I made breakfast for you", exampleEs: "Hice el desayuno para ti", pronunciation: "ˈbrekfəst" },
    { word: "Dinner", translation: "Cena", exampleEn: "Let's cook dinner together", exampleEs: "Cocinemos la cena juntos", pronunciation: "ˈdɪnər" },
    { word: "Laugh", translation: "Reír", exampleEn: "You always make me laugh", exampleEs: "Siempre me haces reír", pronunciation: "læf" },
    { word: "Dance", translation: "Bailar", exampleEn: "Dance with me in the kitchen", exampleEs: "Baila conmigo en la cocina", pronunciation: "dæns" },
    { word: "Surprise", translation: "Sorpresa", exampleEn: "I have a surprise for you", exampleEs: "Tengo una sorpresa para ti", pronunciation: "sərˈpraɪz" },
    { word: "Journey", translation: "Viaje", exampleEn: "Life is a journey we share", exampleEs: "La vida es un viaje que compartimos", pronunciation: "ˈdʒɜːrni" },
    { word: "Peaceful", translation: "Pacífico", exampleEn: "Being with you is so peaceful", exampleEs: "Estar contigo es tan pacífico", pronunciation: "ˈpiːsfəl" },
    { word: "Gentle", translation: "Gentil", exampleEn: "Your gentle touch calms me", exampleEs: "Tu toque gentil me calma", pronunciation: "ˈdʒentəl" },
    { word: "Warm", translation: "Cálido", exampleEn: "Your warm smile makes my day", exampleEs: "Tu cálida sonrisa alegra mi día", pronunciation: "wɔːrm" },
    { word: "Shine", translation: "Brillar", exampleEn: "You shine like a star", exampleEs: "Brillas como una estrella", pronunciation: "ʃaɪn" },
    { word: "Protect", translation: "Proteger", exampleEn: "I will always protect you", exampleEs: "Siempre te protegeré", pronunciation: "prəˈtekt" },
    { word: "Lucky", translation: "Afortunado/a", exampleEn: "I feel so lucky to have you", exampleEs: "Me siento tan afortunado de tenerte", pronunciation: "ˈlʌki" },
    { word: "Cooking", translation: "Cocinar", exampleEn: "I love cooking with you", exampleEs: "Me encanta cocinar contigo", pronunciation: "ˈkʊkɪŋ" },
    { word: "Movie", translation: "Película", exampleEn: "Let's watch a movie tonight", exampleEs: "Veamos una película esta noche", pronunciation: "ˈmuːvi" },
    { word: "Strong", translation: "Fuerte", exampleEn: "Our love is strong", exampleEs: "Nuestro amor es fuerte", pronunciation: "strɔːŋ" },
    { word: "Believe", translation: "Creer", exampleEn: "I believe in us", exampleEs: "Creo en nosotros", pronunciation: "bɪˈliːv" },
    { word: "Home", translation: "Hogar", exampleEn: "Home is wherever you are", exampleEs: "El hogar es donde estés tú", pronunciation: "hoʊm" },
    { word: "Kindness", translation: "Amabilidad", exampleEn: "Your kindness inspires me", exampleEs: "Tu amabilidad me inspira", pronunciation: "ˈkaɪndnəs" },
    { word: "Thoughtful", translation: "Considerado/a", exampleEn: "You are so thoughtful", exampleEs: "Eres tan considerado/a", pronunciation: "ˈθɔːtfəl" },
    { word: "Moonlight", translation: "Luz de luna", exampleEn: "Walking under the moonlight", exampleEs: "Caminando bajo la luz de luna", pronunciation: "ˈmuːnlaɪt" },
    { word: "Treasure", translation: "Tesoro", exampleEn: "You are my greatest treasure", exampleEs: "Eres mi mayor tesoro", pronunciation: "ˈtreʒər" },
    { word: "Patience", translation: "Paciencia", exampleEn: "Thank you for your patience", exampleEs: "Gracias por tu paciencia", pronunciation: "ˈpeɪʃəns" },
    { word: "Journey", translation: "Camino", exampleEn: "Our journey has just begun", exampleEs: "Nuestro camino acaba de empezar", pronunciation: "ˈdʒɜːrni" },
    { word: "Bloom", translation: "Florecer", exampleEn: "Our love continues to bloom", exampleEs: "Nuestro amor sigue floreciendo", pronunciation: "bluːm" },
    { word: "Comfort", translation: "Consuelo", exampleEn: "You are my comfort zone", exampleEs: "Eres mi zona de consuelo", pronunciation: "ˈkʌmfərt" },
    { word: "Raindrops", translation: "Gotas de lluvia", exampleEn: "Listening to raindrops together", exampleEs: "Escuchando gotas de lluvia juntos", pronunciation: "ˈreɪndrɑːps" },
    { word: "Playful", translation: "Juguetón/a", exampleEn: "I love your playful side", exampleEs: "Amo tu lado juguetón", pronunciation: "ˈpleɪfəl" },
    { word: "Faithful", translation: "Fiel", exampleEn: "I am faithful to you", exampleEs: "Soy fiel a ti", pronunciation: "ˈfeɪθfəl" },
    { word: "Butterfly", translation: "Mariposa", exampleEn: "You give me butterflies", exampleEs: "Me das mariposas en el estómago", pronunciation: "ˈbʌtərflaɪ" },
    { word: "Pillow", translation: "Almohada", exampleEn: "Fighting with pillows is fun", exampleEs: "Pelear con almohadas es divertido", pronunciation: "ˈpɪloʊ" },
    { word: "Starlight", translation: "Luz de estrellas", exampleEn: "You are my starlight", exampleEs: "Eres mi luz de estrellas", pronunciation: "ˈstɑːrlaɪt" },
    { word: "Soulmate", translation: "Alma gemela", exampleEn: "You are my soulmate", exampleEs: "Eres mi alma gemela", pronunciation: "ˈsoʊlmeɪt" },
    { word: "Grateful", translation: "Agradecido", exampleEn: "I am grateful every day", exampleEs: "Estoy agradecido cada día", pronunciation: "ˈɡreɪtfəl" },
    { word: "Laughter", translation: "Risa", exampleEn: "Our home is full of laughter", exampleEs: "Nuestro hogar está lleno de risa", pronunciation: "ˈlæftər" },
    { word: "Priceless", translation: "Invaluable", exampleEn: "Your love is priceless", exampleEs: "Tu amor es invaluable", pronunciation: "ˈpraɪsləs" },
    { word: "Silly", translation: "Tonto/a", exampleEn: "I love being silly with you", exampleEs: "Me encanta ser tonto contigo", pronunciation: "ˈsɪli" },
    { word: "Respect", translation: "Respeto", exampleEn: "Respect is the foundation of love", exampleEs: "El respeto es la base del amor", pronunciation: "rɪˈspekt" },
    { word: "Blanket", translation: "Cobija", exampleEn: "Share the blanket with me", exampleEs: "Comparte la cobija conmigo", pronunciation: "ˈblæŋkɪt" },
    { word: "Candle", translation: "Vela", exampleEn: "A candle-lit dinner for two", exampleEs: "Una cena con velas para dos", pronunciation: "ˈkændəl" },
    { word: "Melody", translation: "Melodía", exampleEn: "You are the melody of my life", exampleEs: "Eres la melodía de mi vida", pronunciation: "ˈmelədi" },
    { word: "Peaceful", translation: "Tranquilo", exampleEn: "A peaceful evening at home", exampleEs: "Una noche tranquila en casa", pronunciation: "ˈpiːsfəl" },
    { word: "Sparkle", translation: "Brillar", exampleEn: "Your eyes sparkle when you laugh", exampleEs: "Tus ojos brillan cuando ríes", pronunciation: "ˈspɑːrkəl" },
    { word: "Whisper", translation: "Susurrar", exampleEn: "I whisper 'I love you' every night", exampleEs: "Susurro 'te amo' cada noche", pronunciation: "ˈwɪspər" },
    { word: "Ocean", translation: "Océano", exampleEn: "My love for you is deep as the ocean", exampleEs: "Mi amor por ti es profundo como el océano", pronunciation: "ˈoʊʃən" },
    { word: "Sunrise", translation: "Amanecer", exampleEn: "Watching the sunrise together", exampleEs: "Viendo el amanecer juntos", pronunciation: "ˈsʌnraɪz" },
    { word: "Embrace", translation: "Abrazar", exampleEn: "I want to embrace you tight", exampleEs: "Quiero abrazarte fuerte", pronunciation: "ɪmˈbreɪs" },
    { word: "Flower", translation: "Flor", exampleEn: "A flower for my flower", exampleEs: "Una flor para mi flor", pronunciation: "ˈflaʊər" },
    { word: "Wonder", translation: "Maravilla", exampleEn: "You fill me with wonder", exampleEs: "Me llenas de maravilla", pronunciation: "ˈwʌndər" },
    { word: "Grateful", translation: "Agradecido", exampleEn: "So grateful for your love", exampleEs: "Tan agradecido por tu amor", pronunciation: "ˈɡreɪtfəl" },
    { word: "Magic", translation: "Magia", exampleEn: "Our love is pure magic", exampleEs: "Nuestro amor es pura magia", pronunciation: "ˈmædʒɪk" },
    { word: "Garden", translation: "Jardín", exampleEn: "Let's plant a garden together", exampleEs: "Plantemos un jardín juntos", pronunciation: "ˈɡɑːrdən" },
    { word: "Recipe", translation: "Receta", exampleEn: "We tried a new recipe today", exampleEs: "Probamos una receta nueva hoy", pronunciation: "ˈresɪpi" },
    { word: "Cloud", translation: "Nube", exampleEn: "You make me feel on cloud nine", exampleEs: "Me haces sentir en las nubes", pronunciation: "klaʊd" },
    { word: "Harmony", translation: "Armonía", exampleEn: "We live in perfect harmony", exampleEs: "Vivimos en perfecta armonía", pronunciation: "ˈhɑːrməni" },
    { word: "Couch", translation: "Sofá", exampleEn: "Let's relax on the couch", exampleEs: "Relajémonos en el sofá", pronunciation: "kaʊtʃ" },
    { word: "Rainbow", translation: "Arcoíris", exampleEn: "You are my rainbow after the rain", exampleEs: "Eres mi arcoíris después de la lluvia", pronunciation: "ˈreɪnboʊ" },
    { word: "Honest", translation: "Honesto/a", exampleEn: "I am always honest with you", exampleEs: "Siempre soy honesto contigo", pronunciation: "ˈɑːnɪst" },
    { word: "Understand", translation: "Entender", exampleEn: "You understand me like no one else", exampleEs: "Me entiendes como nadie más", pronunciation: "ˌʌndərˈstænd" },
    { word: "Grateful", translation: "Agradecida", exampleEn: "I am grateful for every moment", exampleEs: "Estoy agradecida por cada momento", pronunciation: "ˈɡreɪtfəl" },
    { word: "Glow", translation: "Resplandecer", exampleEn: "You glow when you are happy", exampleEs: "Resplandeces cuando estás feliz", pronunciation: "ɡloʊ" },
    { word: "Snuggle", translation: "Acurrucarse", exampleEn: "Let's snuggle in bed", exampleEs: "Acurrucémonos en la cama", pronunciation: "ˈsnʌɡəl" },
    { word: "Window", translation: "Ventana", exampleEn: "Looking through the window with you", exampleEs: "Mirando por la ventana contigo", pronunciation: "ˈwɪndoʊ" },
    { word: "Memories", translation: "Recuerdos", exampleEn: "Making beautiful memories", exampleEs: "Creando hermosos recuerdos", pronunciation: "ˈmemərɪz" },
    { word: "Passionate", translation: "Apasionado/a", exampleEn: "You are passionate about life", exampleEs: "Eres apasionado/a por la vida", pronunciation: "ˈpæʃənət" },
    { word: "Shelter", translation: "Refugio", exampleEn: "You are my shelter from the storm", exampleEs: "Eres mi refugio de la tormenta", pronunciation: "ˈʃeltər" },
    { word: "Imagine", translation: "Imaginar", exampleEn: "Imagine our future together", exampleEs: "Imagina nuestro futuro juntos", pronunciation: "ɪˈmædʒɪn" },
    { word: "Inspire", translation: "Inspirar", exampleEn: "You inspire me every day", exampleEs: "Me inspiras cada día", pronunciation: "ɪnˈspaɪər" },
    { word: "Unique", translation: "Único/a", exampleEn: "Our relationship is unique", exampleEs: "Nuestra relación es única", pronunciation: "juːˈniːk" },
    { word: "Coffee", translation: "Café", exampleEn: "I made you coffee this morning", exampleEs: "Te hice café esta mañana", pronunciation: "ˈkɔːfi" },
    { word: "Relax", translation: "Relajar", exampleEn: "Let's relax and enjoy the day", exampleEs: "Relajémonos y disfrutemos del día", pronunciation: "rɪˈlæks" },
    { word: "Tenderness", translation: "Ternura", exampleEn: "Your tenderness melts my heart", exampleEs: "Tu ternura derrite mi corazón", pronunciation: "ˈtendərnəs" },
    { word: "Horizon", translation: "Horizonte", exampleEn: "Our love stretches to the horizon", exampleEs: "Nuestro amor se extiende al horizonte", pronunciation: "həˈraɪzən" },
    { word: "Bliss", translation: "Dicha", exampleEn: "Pure bliss being with you", exampleEs: "Pura dicha estar contigo", pronunciation: "blɪs" },
    { word: "Affection", translation: "Afecto", exampleEn: "I show my affection every day", exampleEs: "Muestro mi afecto cada día", pronunciation: "əˈfekʃən" },
    { word: "Delight", translation: "Deleite", exampleEn: "It is a delight to wake up next to you", exampleEs: "Es un deleite despertar a tu lado", pronunciation: "dɪˈlaɪt" },
    { word: "Nurture", translation: "Nutrir", exampleEn: "We nurture our relationship daily", exampleEs: "Nutrimos nuestra relación a diario", pronunciation: "ˈnɜːrtʃər" },
    { word: "Devotion", translation: "Devoción", exampleEn: "My devotion to you is endless", exampleEs: "Mi devoción por ti es infinita", pronunciation: "dɪˈvoʊʃən" },
    { word: "Sanctuary", translation: "Santuario", exampleEn: "Our home is our sanctuary", exampleEs: "Nuestro hogar es nuestro santuario", pronunciation: "ˈsæŋktʃueri" },
    { word: "Companion", translation: "Compañero/a", exampleEn: "You are my companion in life", exampleEs: "Eres mi compañero/a de vida", pronunciation: "kəmˈpænjən" },
    { word: "Belong", translation: "Pertenecer", exampleEn: "I belong with you", exampleEs: "Pertenezco a tu lado", pronunciation: "bɪˈlɔːŋ" },
    { word: "Grateful", translation: "Agradecido", exampleEn: "Forever grateful for your love", exampleEs: "Siempre agradecido por tu amor", pronunciation: "ˈɡreɪtfəl" },
    { word: "Breathtaking", translation: "Impresionante", exampleEn: "You are breathtaking", exampleEs: "Eres impresionante", pronunciation: "ˈbreθteɪkɪŋ" },
    { word: "Destiny", translation: "Destino", exampleEn: "You are my destiny", exampleEs: "Eres mi destino", pronunciation: "ˈdestɪni" },
    { word: "Loyalty", translation: "Lealtad", exampleEn: "Loyalty is our foundation", exampleEs: "La lealtad es nuestra base", pronunciation: "ˈlɔɪəlti" },
    { word: "Peace", translation: "Paz", exampleEn: "You bring peace to my soul", exampleEs: "Traes paz a mi alma", pronunciation: "piːs" },
    { word: "Strength", translation: "Fuerza", exampleEn: "You give me strength", exampleEs: "Me das fuerza", pronunciation: "streŋθ" },
    { word: "Wisdom", translation: "Sabiduría", exampleEn: "Your wisdom amazes me", exampleEs: "Tu sabiduría me asombra", pronunciation: "ˈwɪzdəm" },
    { word: "Tender", translation: "Tierno/a", exampleEn: "You have a tender heart", exampleEs: "Tienes un corazón tierno", pronunciation: "ˈtendər" },
    { word: "Passion", translation: "Pasión", exampleEn: "Our love is full of passion", exampleEs: "Nuestro amor está lleno de pasión", pronunciation: "ˈpæʃən" },
    { word: "Precious", translation: "Precioso/a", exampleEn: "You are precious to me", exampleEs: "Eres preciosa para mí", pronunciation: "ˈpreʃəs" },
    { word: "Forgive", translation: "Perdonar", exampleEn: "We forgive and grow together", exampleEs: "Perdonamos y crecemos juntos", pronunciation: "fərˈɡɪv" },
    { word: "Grateful", translation: "Agradecida", exampleEn: "Grateful for this life together", exampleEs: "Agradecida por esta vida juntos", pronunciation: "ˈɡreɪtfəl" },
    { word: "Blossom", translation: "Florecer", exampleEn: "Our love blossoms every day", exampleEs: "Nuestro amor florece cada día", pronunciation: "ˈblɑːsəm" },
    { word: "Courage", translation: "Coraje", exampleEn: "You give me courage", exampleEs: "Me das coraje", pronunciation: "ˈkɜːrɪdʒ" },
    { word: "Sparkle", translation: "Chispa", exampleEn: "You add sparkle to my life", exampleEs: "Agregas chispa a mi vida", pronunciation: "ˈspɑːrkəl" },
    { word: "Warmth", translation: "Calidez", exampleEn: "I feel your warmth every night", exampleEs: "Siento tu calidez cada noche", pronunciation: "wɔːrmθ" },
    { word: "Blessing", translation: "Bendición", exampleEn: "You are a blessing in my life", exampleEs: "Eres una bendición en mi vida", pronunciation: "ˈblesɪŋ" },
    { word: "Adore", translation: "Adorar", exampleEn: "I adore you completely", exampleEs: "Te adoro completamente", pronunciation: "əˈdɔːr" },
    { word: "Grace", translation: "Gracia", exampleEn: "You move with such grace", exampleEs: "Te mueves con tanta gracia", pronunciation: "ɡreɪs" },
    { word: "Radiant", translation: "Radiante", exampleEn: "You look radiant today", exampleEs: "Te ves radiante hoy", pronunciation: "ˈreɪdiənt" },
    { word: "Gentle", translation: "Suave", exampleEn: "Your gentle words heal me", exampleEs: "Tus suaves palabras me sanan", pronunciation: "ˈdʒentəl" },
    { word: "Thoughtful", translation: "Atento/a", exampleEn: "Thanks for being so thoughtful", exampleEs: "Gracias por ser tan atento/a", pronunciation: "ˈθɔːtfəl" },
    { word: "Firefly", translation: "Luciérnaga", exampleEn: "You shine like a firefly", exampleEs: "Brillas como una luciérnaga", pronunciation: "ˈfaɪərflaɪ" },
    { word: "Sincere", translation: "Sincero/a", exampleEn: "My love for you is sincere", exampleEs: "Mi amor por ti es sincero", pronunciation: "sɪnˈsɪr" },
    { word: "Enchanting", translation: "Encantador/a", exampleEn: "You are enchanting", exampleEs: "Eres encantador/a", pronunciation: "ɪnˈtʃæntɪŋ" },
    { word: "Serenity", translation: "Serenidad", exampleEn: "You bring serenity to my life", exampleEs: "Traes serenidad a mi vida", pronunciation: "səˈrenɪti" },
    { word: "Bridge", translation: "Puente", exampleEn: "Love is the bridge between us", exampleEs: "El amor es el puente entre nosotros", pronunciation: "brɪdʒ" },
    { word: "Infinite", translation: "Infinito", exampleEn: "My love for you is infinite", exampleEs: "Mi amor por ti es infinito", pronunciation: "ˈɪnfɪnɪt" },
    { word: "Refresh", translation: "Refrescar", exampleEn: "Your love refreshes my soul", exampleEs: "Tu amor refresca mi alma", pronunciation: "rɪˈfreʃ" },
    { word: "Shelter", translation: "Amparo", exampleEn: "I find shelter in your arms", exampleEs: "Encuentro amparo en tus brazos", pronunciation: "ˈʃeltər" },
    { word: "Lighthouse", translation: "Faro", exampleEn: "You are my lighthouse", exampleEs: "Eres mi faro", pronunciation: "ˈlaɪthaʊs" },
    { word: "Anchor", translation: "Ancla", exampleEn: "You are my anchor", exampleEs: "Eres mi ancla", pronunciation: "ˈæŋkər" },
    { word: "Companion", translation: "Compañía", exampleEn: "I love your companion", exampleEs: "Amo tu compañía", pronunciation: "kəmˈpænjən" },
    { word: "Tender", translation: "Tierno", exampleEn: "A tender kiss goodnight", exampleEs: "Un tierno beso de buenas noches", pronunciation: "ˈtendər" },
    { word: "Eternal", translation: "Eterno", exampleEn: "Our bond is eternal", exampleEs: "Nuestro vínculo es eterno", pronunciation: "ɪˈtɜːrnəl" },
    { word: "Heartbeat", translation: "Latido", exampleEn: "My heartbeat races when I see you", exampleEs: "Mi latido se acelera cuando te veo", pronunciation: "ˈhɑːrtbiːt" },
    { word: "Sunshine", translation: "Rayo de sol", exampleEn: "You are my sunshine", exampleEs: "Eres mi rayo de sol", pronunciation: "ˈsʌnʃaɪn" },
    { word: "Caress", translation: "Caricia", exampleEn: "A gentle caress on your cheek", exampleEs: "Una suave caricia en tu mejilla", pronunciation: "kəˈres" },
    { word: "Grateful", translation: "Agradecido", exampleEn: "Always grateful for your smile", exampleEs: "Siempre agradecido por tu sonrisa", pronunciation: "ˈɡreɪtfəl" },
    { word: "Fairy tale", translation: "Cuento de hadas", exampleEn: "Our love is a fairy tale", exampleEs: "Nuestro amor es un cuento de hadas", pronunciation: "ˈferiteɪl" },
    { word: "Wish", translation: "Deseo", exampleEn: "You are my every wish", exampleEs: "Eres cada uno de mis deseos", pronunciation: "wɪʃ" },
    { word: "Honey", translation: "Miel", exampleEn: "Good morning, honey", exampleEs: "Buenos días, miel", pronunciation: "ˈhʌni" },
    { word: "Grateful", translation: "Agradecida", exampleEn: "Grateful for love that grows", exampleEs: "Agradecida por el amor que crece", pronunciation: "ˈɡreɪtfəl" },
    { word: "Adventure", translation: "Aventura", exampleEn: "Let's go on an adventure", exampleEs: "Vamos a una aventura", pronunciation: "ədˈventʃər" },
    { word: "Giggle", translation: "Risita", exampleEn: "Your giggle is contagious", exampleEs: "Tu risita es contagiosa", pronunciation: "ˈɡɪɡəl" },
    { word: "Puzzle", translation: "Rompecabezas", exampleEn: "You complete my puzzle", exampleEs: "Completas mi rompecabezas", pronunciation: "ˈpʌzəl" },
    { word: "Dazzling", translation: "Deslumbrante", exampleEn: "You are dazzling tonight", exampleEs: "Estás deslumbrante esta noche", pronunciation: "ˈdæzlɪŋ" },
    { word: "Comfort", translation: "Comodidad", exampleEn: "Your presence is my comfort", exampleEs: "Tu presencia es mi comodidad", pronunciation: "ˈkʌmfərt" },
    { word: "Champion", translation: "Campeón", exampleEn: "You are my champion", exampleEs: "Eres mi campeón", pronunciation: "ˈtʃæmpiən" },
    { word: "Wonderful", translation: "Increíble", exampleEn: "Life with you is wonderful", exampleEs: "La vida contigo es increíble", pronunciation: "ˈwʌndərfəl" },
    { word: "Charm", translation: "Encanto", exampleEn: "You have endless charm", exampleEs: "Tienes un encanto infinito", pronunciation: "tʃɑːrm" },
    { word: "Devotion", translation: "Entrega", exampleEn: "My devotion knows no limits", exampleEs: "Mi entrega no tiene límites", pronunciation: "dɪˈvoʊʃən" },
    { word: "Melody", translation: "Canción", exampleEn: "You are the melody of my heart", exampleEs: "Eres la canción de mi corazón", pronunciation: "ˈmelədi" },
    { word: "Haven", translation: "Refugio", exampleEn: "You are my safe haven", exampleEs: "Eres mi refugio seguro", pronunciation: "ˈheɪvən" },
    { word: "Twinkle", translation: "Centellear", exampleEn: "Your eyes twinkle brightly", exampleEs: "Tus ojos centellean brillantemente", pronunciation: "ˈtwɪŋkəl" },
    { word: "Miracle", translation: "Milagro", exampleEn: "You are my miracle", exampleEs: "Eres mi milagro", pronunciation: "ˈmɪrəkəl" },
    { word: "Velvet", translation: "Terciopelo", exampleEn: "Soft as velvet, your touch", exampleEs: "Suave como terciopelo, tu toque", pronunciation: "ˈvelvɪt" },
    { word: "Wander", translation: "Pasear", exampleEn: "Let's wander through the park", exampleEs: "Paseemos por el parque", pronunciation: "ˈwɑːndər" },
    { word: "Grateful", translation: "Agradecido", exampleEn: "Grateful just to hold your hand", exampleEs: "Agradecido solo por tomar tu mano", pronunciation: "ˈɡreɪtfəl" },
    { word: "Promise", translation: "Juramento", exampleEn: "My promise to love you always", exampleEs: "Mi juramento de amarte siempre", pronunciation: "ˈprɑːmɪs" },
    { word: "Horizon", translation: "Horizonte", exampleEn: "Let's chase the horizon", exampleEs: "Persigamos el horizonte", pronunciation: "həˈraɪzən" },
    { word: "Serenade", translation: "Serenata", exampleEn: "I want to serenade you", exampleEs: "Quiero darte una serenata", pronunciation: "ˌserəˈneɪd" },
    { word: "Voyage", translation: "Travesía", exampleEn: "Our love is a beautiful voyage", exampleEs: "Nuestro amor es una hermosa travesía", pronunciation: "ˈvɔɪɪdʒ" },
    { word: "Wholesome", translation: "Saludable", exampleEn: "Our relationship is wholesome", exampleEs: "Nuestra relación es saludable", pronunciation: "ˈhoʊlsəm" },
    { word: "Grateful", translation: "Agradecida", exampleEn: "Grateful for lazy Sundays", exampleEs: "Agradecida por domingos relajados", pronunciation: "ˈɡreɪtfəl" },
    { word: "Bloom", translation: "Brotar", exampleEn: "Love blooms in unexpected places", exampleEs: "El amor brota en lugares inesperados", pronunciation: "bluːm" },
    { word: "Endure", translation: "Perdurar", exampleEn: "Our love will endure forever", exampleEs: "Nuestro amor perdurará por siempre", pronunciation: "ɪnˈdʊr" },
    { word: "Elevate", translation: "Elevar", exampleEn: "You elevate my soul", exampleEs: "Elevas mi alma", pronunciation: "ˈeləveɪt" },
    { word: "Gratitude", translation: "Gratitud", exampleEn: "Filled with gratitude for you", exampleEs: "Lleno de gratitud por ti", pronunciation: "ˈɡrætɪtuːd" },
    { word: "Captivate", translation: "Cautivar", exampleEn: "You captivate me every time", exampleEs: "Me cautivas cada vez", pronunciation: "ˈkæptɪveɪt" },
    { word: "Serene", translation: "Sereno/a", exampleEn: "A serene evening with you", exampleEs: "Una noche serena contigo", pronunciation: "səˈriːn" },
    { word: "Fulfillment", translation: "Plenitud", exampleEn: "With you I feel fulfillment", exampleEs: "Contigo siento plenitud", pronunciation: "fʊlˈfɪlmənt" },
    { word: "Nurture", translation: "Cuidar", exampleEn: "We nurture each other's dreams", exampleEs: "Cuidamos los sueños del otro", pronunciation: "ˈnɜːrtʃər" },
    { word: "Resilience", translation: "Resiliencia", exampleEn: "Our love shows resilience", exampleEs: "Nuestro amor muestra resiliencia", pronunciation: "rɪˈzɪliəns" },
    { word: "Empower", translation: "Empoderar", exampleEn: "You empower me to be better", exampleEs: "Me empoderas para ser mejor", pronunciation: "ɪmˈpaʊər" },
    { word: "Mindful", translation: "Consciente", exampleEn: "Being mindful of your needs", exampleEs: "Siendo consciente de tus necesidades", pronunciation: "ˈmaɪndfəl" },
    { word: "Flourish", translation: "Prosperar", exampleEn: "Together we flourish", exampleEs: "Juntos prosperamos", pronunciation: "ˈflɜːrɪʃ" },
    { word: "Tranquil", translation: "Tranquilo", exampleEn: "A tranquil moment together", exampleEs: "Un momento tranquilo juntos", pronunciation: "ˈtræŋkwɪl" },
    { word: "Illuminate", translation: "Iluminar", exampleEn: "You illuminate my darkest days", exampleEs: "Iluminas mis días más oscuros", pronunciation: "ɪˈluːmɪneɪt" },
    { word: "Compassion", translation: "Compasión", exampleEn: "Your compassion knows no bounds", exampleEs: "Tu compasión no tiene límites", pronunciation: "kəmˈpæʃən" },
    { word: "Authentic", translation: "Auténtico/a", exampleEn: "Be authentic, always", exampleEs: "Sé auténtico/a, siempre", pronunciation: "ɔːˈθentɪk" },
    { word: "Spectacular", translation: "Espectacular", exampleEn: "Our love story is spectacular", exampleEs: "Nuestra historia de amor es espectacular", pronunciation: "spekˈtækjələr" },
    { word: "Harmony", translation: "Concordia", exampleEn: "Living in harmony together", exampleEs: "Viviendo en concordia juntos", pronunciation: "ˈhɑːrməni" },
    { word: "Vibrant", translation: "Vibrante", exampleEn: "Your personality is vibrant", exampleEs: "Tu personalidad es vibrante", pronunciation: "ˈvaɪbrənt" },
    { word: "Magnificent", translation: "Magnífico/a", exampleEn: "You are magnificent", exampleEs: "Eres magnífico/a", pronunciation: "mæɡˈnɪfɪsənt" },
    { word: "Grateful", translation: "Agradecido", exampleEn: "Grateful for morning coffee together", exampleEs: "Agradecido por el café de la mañana juntos", pronunciation: "ˈɡreɪtfəl" },
    { word: "Devotion", translation: "Adoración", exampleEn: "My devotion grows stronger daily", exampleEs: "Mi adoración crece más fuerte cada día", pronunciation: "dɪˈvoʊʃən" },
    { word: "Loyalty", translation: "Fidelidad", exampleEn: "Loyalty defines our love", exampleEs: "La fidelidad define nuestro amor", pronunciation: "ˈlɔɪəlti" },
    { word: "Genuine", translation: "Genuino/a", exampleEn: "My feelings are genuine", exampleEs: "Mis sentimientos son genuinos", pronunciation: "ˈdʒenjuɪn" },
    { word: "Euphoria", translation: "Euforia", exampleEn: "Being with you is euphoria", exampleEs: "Estar contigo es euforia", pronunciation: "juːˈfɔːriə" },
    { word: "Mesmerize", translation: "Hipnotizar", exampleEn: "You mesmerize me", exampleEs: "Me hipnotizas", pronunciation: "ˈmezməraɪz" },
    { word: "Cherish", translation: "Atesorar", exampleEn: "I cherish our time together", exampleEs: "Atesoro nuestro tiempo juntos", pronunciation: "ˈtʃerɪʃ" },
    { word: "Resilient", translation: "Resiliente", exampleEn: "We are resilient together", exampleEs: "Somos resilientes juntos", pronunciation: "rɪˈzɪliənt" },
    { word: "Eternity", translation: "Eternidad", exampleEn: "I would wait an eternity for you", exampleEs: "Esperaría una eternidad por ti", pronunciation: "ɪˈtɜːrnɪti" },
    { word: "Treasure", translation: "Atesorar", exampleEn: "I treasure every day with you", exampleEs: "Atesoro cada día contigo", pronunciation: "ˈtreʒər" },
    { word: "Faithful", translation: "Leal", exampleEn: "Faithful to you always", exampleEs: "Leal a ti siempre", pronunciation: "ˈfeɪθfəl" },
    { word: "Wholeheartedly", translation: "De todo corazón", exampleEn: "I love you wholeheartedly", exampleEs: "Te amo de todo corazón", pronunciation: "ˌhoʊlˈhɑːrtɪdli" },
    { word: "Cherished", translation: "Apreciado/a", exampleEn: "You are deeply cherished", exampleEs: "Eres profundamente apreciado/a", pronunciation: "ˈtʃerɪʃt" },
    { word: "Paradise", translation: "Paraíso", exampleEn: "Being with you is paradise", exampleEs: "Estar contigo es un paraíso", pronunciation: "ˈpærədaɪs" },
    { word: "Grateful", translation: "Agradecido", exampleEn: "Grateful for quiet nights at home", exampleEs: "Agradecido por noches tranquilas en casa", pronunciation: "ˈɡreɪtfəl" },
    { word: "Unconditional", translation: "Incondicional", exampleEn: "My love is unconditional", exampleEs: "Mi amor es incondicional", pronunciation: "ˌʌnkənˈdɪʃənəl" },
    { word: "Magnetic", translation: "Magnético/a", exampleEn: "Your smile is magnetic", exampleEs: "Tu sonrisa es magnética", pronunciation: "mæɡˈnetɪk" },
    { word: "Daydream", translation: "Soñar despierto", exampleEn: "I daydream about us", exampleEs: "Sueño despierto sobre nosotros", pronunciation: "ˈdeɪdriːm" },
    { word: "Adorable", translation: "Adorable", exampleEn: "You are absolutely adorable", exampleEs: "Eres absolutamente adorable", pronunciation: "əˈdɔːrəbəl" },
    { word: "Sanctuary", translation: "Oasis", exampleEn: "Our love is my sanctuary", exampleEs: "Nuestro amor es mi oasis", pronunciation: "ˈsæŋktʃueri" },
    { word: "Invincible", translation: "Invencible", exampleEn: "Together we are invincible", exampleEs: "Juntos somos invencibles", pronunciation: "ɪnˈvɪnsəbəl" },
    { word: "Goofy", translation: "Gracioso/a", exampleEn: "Being goofy together is the best", exampleEs: "Ser graciosos juntos es lo mejor", pronunciation: "ˈɡuːfi" },
    { word: "Embrace", translation: "Acoger", exampleEn: "I embrace every part of you", exampleEs: "Acojo cada parte de ti", pronunciation: "ɪmˈbreɪs" },
    { word: "Soothe", translation: "Calmar", exampleEn: "Your voice soothes me", exampleEs: "Tu voz me calma", pronunciation: "suːð" },
    { word: "Celebrate", translation: "Celebrar", exampleEn: "Let's celebrate our love", exampleEs: "Celebremos nuestro amor", pronunciation: "ˈseləbreɪt" },
    { word: "Incredible", translation: "Increíble", exampleEn: "You are incredible", exampleEs: "Eres increíble", pronunciation: "ɪnˈkredəbəl" },
    { word: "Butterscotch", translation: "Caramelo", exampleEn: "Sweet like butterscotch", exampleEs: "Dulce como el caramelo", pronunciation: "ˈbʌtərskatʃ" },
    { word: "Cherish", translation: "Querer mucho", exampleEn: "I will always cherish you", exampleEs: "Siempre te querré mucho", pronunciation: "ˈtʃerɪʃ" },
    { word: "Unbreakable", translation: "Inquebrantable", exampleEn: "Our bond is unbreakable", exampleEs: "Nuestro vínculo es inquebrantable", pronunciation: "ʌnˈbreɪkəbəl" },
    { word: "Heavenly", translation: "Celestial", exampleEn: "Your cooking is heavenly", exampleEs: "Tu cocina es celestial", pronunciation: "ˈhevənli" },
    { word: "Conquer", translation: "Conquistar", exampleEn: "Together we conquer the world", exampleEs: "Juntos conquistamos el mundo", pronunciation: "ˈkɑːŋkər" },
    { word: "Soulful", translation: "Con alma", exampleEn: "You have soulful eyes", exampleEs: "Tienes ojos con alma", pronunciation: "ˈsoʊlfəl" },
    { word: "Devoted", translation: "Devoto/a", exampleEn: "I am devoted to our family", exampleEs: "Soy devoto/a a nuestra familia", pronunciation: "dɪˈvoʊtɪd" },
    { word: "Exquisite", translation: "Exquisito/a", exampleEn: "Your taste is exquisite", exampleEs: "Tu gusto es exquisito", pronunciation: "ɪkˈskwɪzɪt" },
    { word: "Beloved", translation: "Amado/a", exampleEn: "You are my beloved", exampleEs: "Eres mi amado/a", pronunciation: "bɪˈlʌvɪd" },
    { word: "Magnificent", translation: "Majestuoso", exampleEn: "A magnificent view, like you", exampleEs: "Una vista majestuosa, como tú", pronunciation: "mæɡˈnɪfɪsənt" },
    { word: "Endearment", translation: "Cariño", exampleEn: "Terms of endearment for you", exampleEs: "Palabras de cariño para ti", pronunciation: "ɪnˈdɪrmənt" },
    { word: "Ethereal", translation: "Etéreo/a", exampleEn: "Your beauty is ethereal", exampleEs: "Tu belleza es etérea", pronunciation: "ɪˈθɪriəl" },
    { word: "Timeless", translation: "Atemporal", exampleEn: "Our love is timeless", exampleEs: "Nuestro amor es atemporal", pronunciation: "ˈtaɪmləs" },
    { word: "Enchanted", translation: "Hechizado/a", exampleEn: "I am enchanted by you", exampleEs: "Estoy hechizado/a por ti", pronunciation: "ɪnˈtʃæntɪd" },
    { word: "Yearning", translation: "Anhelo", exampleEn: "A yearning to hold you close", exampleEs: "Un anhelo de tenerte cerca", pronunciation: "ˈjɜːrnɪŋ" },
    { word: "Iridescent", translation: "Iridiscente", exampleEn: "Love is iridescent and colorful", exampleEs: "El amor es iridiscente y colorido", pronunciation: "ˌɪrɪˈdesənt" },
    { word: "Wholesome", translation: "Completo/a", exampleEn: "You make me feel wholesome", exampleEs: "Me haces sentir completo/a", pronunciation: "ˈhoʊlsəm" },
    { word: "Irreplaceable", translation: "Irremplazable", exampleEn: "You are irreplaceable", exampleEs: "Eres irremplazable", pronunciation: "ˌɪrɪˈpleɪsəbəl" },
    { word: "Everlasting", translation: "Imperecedero", exampleEn: "An everlasting bond between us", exampleEs: "Un vínculo imperecedero entre nosotros", pronunciation: "ˌevərˈlæstɪŋ" },
    { word: "Extraordinary", translation: "Extraordinario/a", exampleEn: "You are extraordinary", exampleEs: "Eres extraordinario/a", pronunciation: "ɪkˈstrɔːrdɪneri" },
    { word: "Unforgettable", translation: "Inolvidable", exampleEn: "Every moment is unforgettable", exampleEs: "Cada momento es inolvidable", pronunciation: "ˌʌnfərˈɡetəbəl" },
    { word: "Phenomenal", translation: "Fenomenal", exampleEn: "Our journey is phenomenal", exampleEs: "Nuestro viaje es fenomenal", pronunciation: "fɪˈnɑːmɪnəl" },
    { word: "Resplendent", translation: "Resplandeciente", exampleEn: "You are resplendent", exampleEs: "Eres resplandeciente", pronunciation: "rɪˈsplendənt" },
    { word: "Eloquent", translation: "Elocuente", exampleEn: "Love needs no eloquent words", exampleEs: "El amor no necesita palabras elocuentes", pronunciation: "ˈeləkwənt" },
    { word: "Quintessential", translation: "Esencial", exampleEn: "You are the quintessential partner", exampleEs: "Eres la pareja esencial", pronunciation: "ˌkwɪntɪˈsenʃəl" },
    { word: "Ineffable", translation: "Indescriptible", exampleEn: "My love for you is ineffable", exampleEs: "Mi amor por ti es indescriptible", pronunciation: "ɪnˈefəbəl" },
    { word: "Effervescent", translation: "Efervescente", exampleEn: "Your personality is effervescent", exampleEs: "Tu personalidad es efervescente", pronunciation: "ˌefərˈvesənt" },
    { word: "Empathy", translation: "Empatía", exampleEn: "Your empathy makes you special", exampleEs: "Tu empatía te hace especial", pronunciation: "ˈempəθi" },
    { word: "Gratitude", translation: "Agradecimiento", exampleEn: "Overflowing with gratitude", exampleEs: "Rebosando de agradecimiento", pronunciation: "ˈɡrætɪtuːd" },
    { word: "Vulnerable", translation: "Vulnerable", exampleEn: "Being vulnerable with you is safe", exampleEs: "Ser vulnerable contigo es seguro", pronunciation: "ˈvʌlnərəbəl" },
    { word: "Intentional", translation: "Intencional", exampleEn: "Our love is intentional", exampleEs: "Nuestro amor es intencional", pronunciation: "ɪnˈtenʃənəl" },
    { word: "Boundless", translation: "Ilimitado", exampleEn: "My love for you is boundless", exampleEs: "Mi amor por ti es ilimitado", pronunciation: "ˈbaʊndləs" },
    { word: "Captivating", translation: "Cautivador/a", exampleEn: "Your eyes are captivating", exampleEs: "Tus ojos son cautivadores", pronunciation: "ˈkæptɪveɪtɪŋ" },
    { word: "Luminous", translation: "Luminoso/a", exampleEn: "Your smile is luminous", exampleEs: "Tu sonrisa es luminosa", pronunciation: "ˈluːmɪnəs" },
    { word: "Steadfast", translation: "Inquebrantable", exampleEn: "My love is steadfast", exampleEs: "Mi amor es inquebrantable", pronunciation: "ˈstedfæst" },
    { word: "Serendipity", translation: "Serendipia", exampleEn: "Meeting you was serendipity", exampleEs: "Conocerte fue serendipia", pronunciation: "ˌserənˈdɪpɪti" },
    { word: "Admire", translation: "Admirar", exampleEn: "I admire your strength", exampleEs: "Admiro tu fuerza", pronunciation: "ədˈmaɪər" },
    { word: "Resilience", translation: "Fortaleza", exampleEn: "Our resilience is beautiful", exampleEs: "Nuestra fortaleza es hermosa", pronunciation: "rɪˈzɪliəns" },
    { word: "Heritage", translation: "Herencia", exampleEn: "Our love becomes our heritage", exampleEs: "Nuestro amor se convierte en nuestra herencia", pronunciation: "ˈherɪtɪdʒ" },
    { word: "Kaleidoscope", translation: "Caleidoscopio", exampleEn: "Love is a kaleidoscope of emotions", exampleEs: "El amor es un caleidoscopio de emociones", pronunciation: "kəˈlaɪdəskoʊp" },
    { word: "Wavelength", translation: "Sintonía", exampleEn: "We are on the same wavelength", exampleEs: "Estamos en la misma sintonía", pronunciation: "ˈweɪvleŋθ" },
    { word: "Cornerstone", translation: "Piedra angular", exampleEn: "Trust is the cornerstone of love", exampleEs: "La confianza es la piedra angular del amor", pronunciation: "ˈkɔːrnərstoʊn" },
    { word: "Wanderlust", translation: "Pasión por viajar", exampleEn: "Sharing wanderlust with you", exampleEs: "Compartiendo la pasión por viajar contigo", pronunciation: "ˈwɑːndərlʌst" },
    { word: "Spectacular", translation: "Asombroso/a", exampleEn: "You make life spectacular", exampleEs: "Haces la vida asombrosa", pronunciation: "spekˈtækjələr" },
    { word: "Constellation", translation: "Constelación", exampleEn: "You are my constellation", exampleEs: "Eres mi constelación", pronunciation: "ˌkɑːnstəˈleɪʃən" },
    { word: "Fellowship", translation: "Compañerismo", exampleEn: "Our fellowship is unshakeable", exampleEs: "Nuestro compañerismo es inquebrantable", pronunciation: "ˈfeloʊʃɪp" },
    { word: "Remarkable", translation: "Notable", exampleEn: "You are truly remarkable", exampleEs: "Eres verdaderamente notable", pronunciation: "rɪˈmɑːrkəbəl" },
    { word: "Persevere", translation: "Perseverar", exampleEn: "Together, we persevere", exampleEs: "Juntos, perseveramos", pronunciation: "ˌpɜːrsəˈvɪr" },
    { word: "Grateful", translation: "Agradecido/a", exampleEn: "Grateful for a lifetime with you", exampleEs: "Agradecido/a por una vida contigo", pronunciation: "ˈɡreɪtfəl" },
];
